JOBS_DB = [
    {
      "id": 889977,
      "created": "2025-03-01 10:30:00",
      "last_updated": "2025-04-10 16:00:00", 
      "time_posted": "1mo",
      "title": "Data Engineer",
      "description": " We are seeking a Senior Data Engineer, Engineering & Operations to lead the Engineering & Automation pillar. Reporting to the Sr. Director of Engineering & Operations, you will lead the engineering and operational excellence behind our data collaboration ecosystem. You will be instrumental in designing and implementing scalable data architectures and driving automation through AI agents and self-service tooling, translating prototypes into robust production solutions. Duties and Responsibilities:   The person in this role will:   Architecture Leadership: Define partner onboarding and clean room architecture patterns across Snowflake, LiveRamp, and Databricks that are secure, scalable, and repeatable.    Infrastructure Setup & Library Deployment: Configure and manage partner-specific clean room environments; deploy and manage Python-based libraries within the platform ecosystem.    MLOps Integration: Establish and maintain MLOps practices, including model serving, monitoring, and pipeline orchestration for AI/ML features deployed within the platform ecosystem.    Security & RBAC: Own design and enforcement of granular RBAC policies and least-privilege service accounts.    Partner Onboarding: Serve as the technical lead for onboarding new partners, implementing privacy-preserving controls (e.g., aggregation thresholds and anonymization techniques).    Pipeline & Data Product Ownership: Design, build, and operate scalable ELT pipelines using Snowpark and/or PySpark and advanced SQL to provision Gold datasets.    Identity Resolution: Implement and evolve identity resolution logic mapping internal data to 3P identifiers (including LUIDs, RampIDs, TransUnion IDs), ensuring privacy-safe practices.    Scalable Architecture: Design and operate scalable data architectures across Snowflake and Databricks supporting batch and near real-time processing patterns.    Data Quality by Design: Build robust automated checks (e.g., Great Expectations or custom SQL assertions) and define quality standards to detect schema drift, null rate spikes, and volume anomalies.    FinOps & Operational Excellence: Lead performance optimization across platforms (query tuning, caching, incremental processing) and define and implement query tagging and chargeback models for accurate cost attribution.    Operational Maturity: Establish monitoring, alerting, runbooks, and standard operating procedures to improve platform reliability and reduce incident time-to-resolution.    Testing & Validation: Validate that output data adheres to privacy and business requirements, and define test strategies for partner-facing releases.    Technical Escalation: Serve as the escalation point for diagnosing connection failures, data discrepancies, or latency issues with partner technical teams.    Agentic Workflows & Platform Enablement: Design and build internal AI agents (using frameworks like LangChain, Snowflake Cortex) and mentor other engineers through code reviews, design discussions, and operational best practices.         Qualifications: Education: Bachelor’s degree or higher in Computer Science, Information Systems, Software, Electrical or Electronics Engineering. Technical Experience: 5+ years of Data Engineering experience, with deep proficiency in advanced SQL and Python. 3+ years of hands-on experience with cloud data platforms, specifically Snowflake or Databricks. Proven experience building and operating scalable ELT pipelines using orchestration tools (e.g., Airflow, dbt). Strong track record designing production-grade systems (observability, reliability, performance tuning, incident response). Specialized Skills: Clean Room Knowledge: Exposure to Data Clean Room concepts and Clean Room platforms like LiveRamp, Snowflake or Databricks. AI/LLM Experience: Experience building applications with LLMs, RAG, Vector Databases, or frameworks like LangChain/LlamaIndex. Leadership: Ability to mentor other engineers through code reviews, design discussions, and operational best practices. Certifications Preferred: SnowPro Core Certification OR Databricks Certified Data Engineer Associate. Certifications Highly Preferred: SnowPro Advanced: Data Engineer OR Databricks Certified Data Engineer Professional. Additional Requirements:     Fully Remote: This position has been designated as fully remote, meaning that the position is expected to contribute from a non-NBCUniversal worksite, most commonly an employee’s residence.      This position is eligible for company sponsored benefits, including medical, dental and vision insurance, 401(k), paid leave, tuition reimbursement, and a variety of other discounts and perks. Learn more about the benefits offered by NBC Universal by visiting the Benefits page of the Careers website. Salary range: $140,000 - $180,000 (bonus eligible)",
      "seniority": "Mid-Senior level",
      "employment_type": "Full-time",
      "location": "San Francisco, CA",
      "url": "https://www.professional-network.com/jobs/view/job-url",
      "company_id": 102938,
      "company_name": "NBC Universal",
      "company_url": "https://www.professional-network.com/company/nbc-company",
      "deleted": 0,
      "application_active": 1,
      "salary": "$20,000 - $40,000",
      "applicants_count": "23",
      "country": "United States"
    },
    {
      "id": 901122,
      "created": "2026-01-15 09:00:00",
      "last_updated": "2026-02-01 14:20:00",
      "time_posted": "2w",
      "title": "Principal Data Engineer (FinTech)",
      "description": "We are looking for a Principal Data Engineer to architect our next-generation financial streaming platform. You will lead the migration from legacy batch processing to a real-time Kafka-based architecture.\n\nKey Responsibilities:\n- Design low-latency streaming pipelines using Flink and Kafka.\n- Lead the data governance initiative across the engineering org.\n- Optimize Snowflake storage costs and query performance.\n\nQualifications:\n- 8+ years in Data Engineering.\n- Expert-level Python and Java/Scala.\n- Deep experience with AWS (Kinesis, MSK, Lambda).",
      "seniority": "Director",
      "employment_type": "Full-time",
      "location": "New York, NY",
      "url": "https://www.professional-network.com/jobs/view/901122",
      "company_id": 445566,
      "company_name": "Apex Finance Systems",
      "company_url": "https://www.professional-network.com/company/apex-finance",
      "deleted": 0,
      "application_active": 1,
      "salary": "$210,000 - $260,000",
      "applicants_count": "45",
      "country": "United States"
    },
    {
      "id": 901123,
      "created": "2026-01-20 08:30:00",
      "last_updated": "2026-01-20 08:30:00",
      "time_posted": "1w",
      "title": "Junior Data Engineer",
      "description": "Join our growing Analytics team to help maintain our dbt projects and BigQuery data warehouse. This is a great role for someone transitioning from Data Analysis into Engineering.\n\nDuties:\n- Write and optimize SQL models in dbt.\n- Monitor Airflow DAGs for failures.\n- Ensure data quality in our Looker dashboards.\n\nQualifications:\n- 1-2 years experience with SQL.\n- Basic understanding of Python and Git.\n- Knowledge of GCP is a plus.",
      "seniority": "Entry level",
      "employment_type": "Full-time",
      "location": "Austin, TX",
      "url": "https://www.professional-network.com/jobs/view/901123",
      "company_id": 778899,
      "company_name": "RetailFlow Inc.",
      "company_url": "https://www.professional-network.com/company/retailflow",
      "deleted": 0,
      "application_active": 1,
      "salary": "$85,000 - $110,000",
      "applicants_count": "156",
      "country": "United States"
    },
    {
      "id": 901124,
      "created": "2026-01-28 11:15:00",
      "last_updated": "2026-02-02 10:00:00",
      "time_posted": "5d",
      "title": "Senior Data Engineer - MLOps",
      "description": "Help us bridge the gap between Data Science and Production. You will build the pipelines that feed our LLM training sets.\n\nResponsibilities:\n- Build vector database pipelines (Pinecone/Weaviate).\n- Deploy model monitoring services.\n- Maintain high-scale PySpark jobs on Databricks.\n\nRequirements:\n- 5+ years experience.\n- Strong background in Spark and Kubernetes.\n- Previous experience with MLflow.",
      "seniority": "Mid-Senior level",
      "employment_type": "Full-time",
      "location": "Remote",
      "url": "https://www.professional-network.com/jobs/view/901124",
      "company_id": 121314,
      "company_name": "NeuralPath AI",
      "company_url": "https://www.professional-network.com/company/neuralpath",
      "deleted": 0,
      "application_active": 1,
      "salary": "$175,000 - $220,000",
      "applicants_count": "89",
      "country": "United States"
    },
    {
      "id": 901125,
      "created": "2026-01-10 16:45:00",
      "last_updated": "2026-01-30 09:00:00",
      "time_posted": "3w",
      "title": "Data Engineer (Contract)",
      "description": "6-month contract to assist with a legacy migration from On-prem Hadoop to Azure Data Factory and Synapse.\n\nTasks:\n- Refactor MapReduce jobs into Spark/Scala.\n- Map legacy schemas to new cloud formats.\n- Technical documentation.\n\nRequired:\n- Strong Azure background.\n- 4+ years of Hadoop/Hive experience.",
      "seniority": "Mid-Senior level",
      "employment_type": "Contract",
      "location": "Chicago, IL",
      "url": "https://www.professional-network.com/jobs/view/901125",
      "company_id": 554433,
      "company_name": "Global Logistics Corp",
      "company_url": "https://www.professional-network.com/company/globallogistics",
      "deleted": 0,
      "application_active": 1,
      "salary": "$80 - $100 /hr",
      "applicants_count": "12",
      "country": "United States"
    },
    {
      "id": 901126,
      "created": "2026-02-01 13:00:00",
      "last_updated": "2026-02-01 13:00:00",
      "time_posted": "1d",
      "title": "Lead Data Infrastructure Engineer",
      "description": "We are seeking a Lead Engineer to manage our core data infrastructure. You won't just build pipelines; you'll build the platform the pipelines run on.\n\nDuties:\n- Manage Terraform scripts for AWS data resources.\n- Optimize Trino/Presto clusters.\n- Implement CI/CD for data deployments.\n\nQualifications:\n- Proficiency in Go or Python.\n- Infrastructure as Code (Terraform/CloudFormation) expert.",
      "seniority": "Mid-Senior level",
      "employment_type": "Full-time",
      "location": "Seattle, WA",
      "url": "https://www.professional-network.com/jobs/view/901126",
      "company_id": 667788,
      "company_name": "CloudScale Systems",
      "company_url": "https://www.professional-network.com/company/cloudscale",
      "deleted": 0,
      "application_active": 1,
      "salary": "$190,000 - $230,000",
      "applicants_count": "31",
      "country": "United States"
    },
    {
      "id": 901127,
      "created": "2026-01-05 10:00:00",
      "last_updated": "2026-02-01 17:30:00",
      "time_posted": "1mo",
      "title": "Healthcare Data Engineer",
      "description": "Focus on building HIPAA-compliant data lakes for patient analytics. You will work closely with medical researchers.\n\nSkills:\n- FHIR/HL7 data standards experience.\n- AWS Glue and Athena.\n- Strong Python and data encryption knowledge.\n\nEducation:\n- MS in Health Informatics or CS preferred.",
      "seniority": "Mid-Senior level",
      "employment_type": "Full-time",
      "location": "Boston, MA",
      "url": "https://www.professional-network.com/jobs/view/901127",
      "company_id": 223344,
      "company_name": "BioHealth Data",
      "company_url": "https://www.professional-network.com/company/biohealth",
      "deleted": 0,
      "application_active": 1,
      "salary": "$135,000 - $170,000",
      "applicants_count": "54",
      "country": "United States"
    },
    {
      "id": 901128,
      "created": "2026-01-25 09:20:00",
      "last_updated": "2026-01-25 09:20:00",
      "time_posted": "1w",
      "title": "Data Engineer - Analytics Engineering",
      "description": "Positioned between software engineering and data analysis, you will focus on building clean, tested datasets for our business users.\n\nTech Stack:\n- dbt Cloud, Snowflake, Fivetran, and Tableau.\n- Heavy emphasis on software best practices (unit testing, documentation).",
      "seniority": "Associate",
      "employment_type": "Full-time",
      "location": "Denver, CO",
      "url": "https://www.professional-network.com/jobs/view/901128",
      "company_id": 990011,
      "company_name": "Mountain Metrics",
      "company_url": "https://www.professional-network.com/company/mountainmetrics",
      "deleted": 0,
      "application_active": 1,
      "salary": "$115,000 - $145,000",
      "applicants_count": "72",
      "country": "United States"
    },
    {
      "id": 901129,
      "created": "2026-01-12 14:00:00",
      "last_updated": "2026-01-20 12:00:00",
      "time_posted": "3w",
      "title": "ETL Developer / Data Engineer",
      "description": "Support our marketing department by consolidating data from 20+ different ad platforms into our centralized warehouse.\n\nRequired:\n- Advanced SQL skills.\n- Experience with Python API integrations.\n- Previous experience with Airbyte or Meltano is a plus.",
      "seniority": "Mid-Senior level",
      "employment_type": "Full-time",
      "location": "Miami, FL",
      "url": "https://www.professional-network.com/jobs/view/901129",
      "company_id": 332211,
      "company_name": "AdReach Agency",
      "company_url": "https://www.professional-network.com/company/adreach",
      "deleted": 0,
      "application_active": 1,
      "salary": "$120,000 - $155,000",
      "applicants_count": "41",
      "country": "United States"
    },
    {
      "id": 901130,
      "created": "2026-02-02 08:00:00",
      "last_updated": "2026-02-02 08:00:00",
      "time_posted": "1h",
      "title": "Staff Data Engineer (Data Mesh focus)",
      "description": "Help us decentralize our data architecture. You will define the standards for 'Data as a Product' across the company.\n\nExperience:\n- Implementing Data Mesh or Data Fabric concepts.\n- High-level architectural design.\n- Strong stakeholder management.",
      "seniority": "Staff",
      "employment_type": "Full-time",
      "location": "Remote",
      "url": "https://www.professional-network.com/jobs/view/901130",
      "company_id": 556677,
      "company_name": "Enterprise Scale Co",
      "company_url": "https://www.professional-network.com/company/enterprisescale",
      "deleted": 0,
      "application_active": 1,
      "salary": "$230,000 - $280,000",
      "applicants_count": "5",
      "country": "United States"
    },
    {
      "id": 901131,
      "created": "2026-01-22 11:30:00",
      "last_updated": "2026-02-01 10:00:00",
      "time_posted": "1w",
      "title": "Data Engineer - Game Analytics",
      "description": "Build the pipelines that track millions of events per second for our flagship mobile titles. \n\nSkills:\n- Java/Kotlin or Scala.\n- Google Cloud Dataflow / Apache Beam.\n- BigQuery and Looker.",
      "seniority": "Mid-Senior level",
      "employment_type": "Full-time",
      "location": "Los Angeles, CA",
      "url": "https://www.professional-network.com/jobs/view/901131",
      "company_id": 884422,
      "company_name": "Starlight Gaming",
      "company_url": "https://www.professional-network.com/company/starlight",
      "deleted": 0,
      "application_active": 1,
      "salary": "$150,000 - $190,000",
      "applicants_count": "112",
      "country": "United States"
    }
  ]

STRUCTURED_JOBS = [
  {'company_name': 'NBC Universal',
		'positions': [{'name': 'Senior Data Engineer',
      'field': 'Engineering & Operations',
      'time_experience': 60.0},
    {'name': 'Data Engineer',
      'field': 'Data Engineering',
      'time_experience': 60.0}],
    'main_position': {'name': 'Senior Data Engineer',
      'field': 'Engineering & Operations',
      'time_experience': 60.0},
    'main_position_name_variations': ['Senior Data Engineer',
    'Engineering & Operations'],
    'hard_skills': [{'description': 'Advanced SQL', 'time_experience': 60.0},
    {'description': 'Python', 'time_experience': 60.0},
    {'description': 'Cloud data platforms (Snowflake, Databricks)',
      'time_experience': 36.0},
    {'description': 'ELT pipelines', 'time_experience': None},
    {'description': 'Orchestration tools (Airflow, dbt)',
      'time_experience': None},
    {'description': 'Production-grade systems design (observability, reliability, performance tuning, incident response)',
      'time_experience': None},
    {'description': 'Data Clean Room concepts', 'time_experience': None},
    {'description': 'Clean Room platforms (LiveRamp, Snowflake, Databricks)',
      'time_experience': None},
    {'description': 'Building applications with LLMs', 'time_experience': None},
    {'description': 'RAG', 'time_experience': None},
    {'description': 'Vector Databases', 'time_experience': None},
    {'description': 'Frameworks like LangChain/LlamaIndex',
      'time_experience': None},
    {'description': 'Snowpark', 'time_experience': None},
    {'description': 'PySpark', 'time_experience': None},
    {'description': 'MLOps practices', 'time_experience': None},
    {'description': 'RBAC policies', 'time_experience': None},
    {'description': 'Identity resolution', 'time_experience': None},
    {'description': 'Automated data quality checks (Great Expectations, custom SQL assertions)',
      'time_experience': None},
    {'description': 'Monitoring and alerting', 'time_experience': None}],
    'soft_skills': ['Leadership',
    'Mentoring',
    'Technical Escalation',
    'Problem-solving',
    'Communication']},
  {'company_name': 'Apex Finance Systems',
		'positions': [{'name': 'Principal Data Engineer',
      'field': 'Data Engineering',
      'time_experience': 96.0}],
    'main_position': {'name': 'Principal Data Engineer',
      'field': 'Data Engineering',
      'time_experience': 96.0},
    'main_position_name_variations': ['Principal Data Engineer'],
    'hard_skills': [{'description': 'Flink', 'time_experience': None},
    {'description': 'Kafka', 'time_experience': None},
    {'description': 'Python', 'time_experience': 96.0},
    {'description': 'Java', 'time_experience': 96.0},
    {'description': 'Scala', 'time_experience': 96.0},
    {'description': 'AWS', 'time_experience': None},
    {'description': 'Kinesis', 'time_experience': None},
    {'description': 'MSK', 'time_experience': None},
    {'description': 'Lambda', 'time_experience': None},
    {'description': 'Snowflake', 'time_experience': None}],
    'soft_skills': ['Data Governance', 'Architecture']},
  {'company_name': 'RetailFlow Inc.',
		'positions': [{'name': 'Data Engineer',
      'field': 'Analytics',
      'time_experience': None},
    {'name': 'Data Analyst', 'field': 'Analytics', 'time_experience': 24.0}],
    'main_position': {'name': 'Data Engineer',
      'field': 'Analytics',
      'time_experience': None},
    'main_position_name_variations': ['Data Engineer', 'Analytics Engineer'],
    'hard_skills': [{'description': 'SQL', 'time_experience': 24.0},
    {'description': 'dbt', 'time_experience': None},
    {'description': 'BigQuery', 'time_experience': None},
    {'description': 'Airflow', 'time_experience': None},
    {'description': 'Looker', 'time_experience': None},
    {'description': 'Python', 'time_experience': None},
    {'description': 'Git', 'time_experience': None},
    {'description': 'GCP', 'time_experience': None}],
    'soft_skills': ['Data Quality Assurance']},
  {'company_name': 'NeuralPath AI',
		'positions': [{'name': 'Data Engineer',
      'field': 'Data Science',
      'time_experience': 60.0},
    {'name': 'Machine Learning Engineer',
      'field': 'Machine Learning',
      'time_experience': 60.0}],
    'main_position': {'name': 'Data Engineer',
      'field': 'Data Science',
      'time_experience': 60.0},
    'main_position_name_variations': ['Data Engineer',
    'MLOps Engineer',
    'Production Data Scientist'],
    'hard_skills': [{'description': 'Vector database pipelines (Pinecone/Weaviate)',
      'time_experience': None},
    {'description': 'Model monitoring services', 'time_experience': None},
    {'description': 'PySpark jobs on Databricks', 'time_experience': None},
    {'description': 'Spark', 'time_experience': 60.0},
    {'description': 'Kubernetes', 'time_experience': 60.0},
    {'description': 'MLflow', 'time_experience': 60.0}],
    'soft_skills': ['Bridging the gap between Data Science and Production',
    'Building pipelines for LLM training sets']},
  {'company_name': 'Global Logistics Corp',
		'positions': [{'name': 'Data Engineer',
      'field': 'Data Engineering',
      'time_experience': None}],
    'main_position': {'name': 'Data Engineer',
      'field': 'Data Engineering',
      'time_experience': None},
    'main_position_name_variations': ['Data Engineer'],
    'hard_skills': [{'description': 'Azure Data Factory',
      'time_experience': None},
    {'description': 'Azure Synapse', 'time_experience': None},
    {'description': 'Spark', 'time_experience': None},
    {'description': 'Scala', 'time_experience': None},
    {'description': 'Hadoop', 'time_experience': 48.0},
    {'description': 'Hive', 'time_experience': 48.0},
    {'description': 'MapReduce', 'time_experience': None},
    {'description': 'Technical documentation', 'time_experience': None}],
    'soft_skills': ['Problem-solving']},
  {'company_name': 'CloudScale Systems',
		'positions': [{'name': 'Lead Engineer',
      'field': 'Data Infrastructure',
      'time_experience': None}],
    'main_position': {'name': 'Lead Engineer',
      'field': 'Data Infrastructure',
      'time_experience': None},
    'main_position_name_variations': ['Lead Engineer'],
    'hard_skills': [{'description': 'Terraform', 'time_experience': None},
    {'description': 'AWS data resources', 'time_experience': None},
    {'description': 'Trino/Presto clusters', 'time_experience': None},
    {'description': 'CI/CD for data deployments', 'time_experience': None},
    {'description': 'Go', 'time_experience': None},
    {'description': 'Python', 'time_experience': None},
    {'description': 'Infrastructure as Code', 'time_experience': None},
    {'description': 'CloudFormation', 'time_experience': None}],
    'soft_skills': ['Management']},
  {'company_name': 'BioHealth Data',
		'positions': [{'name': 'Data Engineer',
      'field': 'Health Informatics',
      'time_experience': None},
    {'name': 'Analytics Engineer',
      'field': 'Health Informatics',
      'time_experience': None}],
    'main_position': {'name': 'Data Engineer',
      'field': 'Health Informatics',
      'time_experience': None},
    'main_position_name_variations': ['Data Engineer',
    'Analytics Engineer',
    'HIPAA-compliant Data Lake Specialist'],
    'hard_skills': [{'description': 'FHIR/HL7 data standards',
      'time_experience': None},
    {'description': 'AWS Glue', 'time_experience': None},
    {'description': 'AWS Athena', 'time_experience': None},
    {'description': 'Python', 'time_experience': None},
    {'description': 'Data encryption', 'time_experience': None}],
    'soft_skills': ['Collaboration with medical researchers',
    'HIPAA compliance']},
  {'company_name': 'Mountain Metrics',
		'positions': [{'name': 'Data Engineer',
      'field': 'Data Engineering',
      'time_experience': None}],
    'main_position': {'name': 'Data Engineer',
      'field': 'Data Engineering',
      'time_experience': None},
    'main_position_name_variations': ['Data Engineer'],
    'hard_skills': [{'description': 'dbt Cloud', 'time_experience': None},
    {'description': 'Snowflake', 'time_experience': None},
    {'description': 'Fivetran', 'time_experience': None},
    {'description': 'Tableau', 'time_experience': None},
    {'description': 'Unit Testing', 'time_experience': None},
    {'description': 'Documentation', 'time_experience': None}],
    'soft_skills': ['Building clean, tested datasets',
    'Software best practices']},
  {'company_name': 'AdReach Agency',
		'positions': [{'name': 'Data Engineer',
      'field': 'Marketing Data',
      'time_experience': None}],
    'main_position': {'name': 'Data Engineer',
      'field': 'Marketing Data',
      'time_experience': None},
    'main_position_name_variations': ['Data Engineer'],
    'hard_skills': [{'description': 'Advanced SQL', 'time_experience': None},
    {'description': 'Python API integrations', 'time_experience': None},
    {'description': 'Airbyte', 'time_experience': None},
    {'description': 'Meltano', 'time_experience': None}],
    'soft_skills': ['Data Consolidation']},
  {'company_name': 'Enterprise Scale Co',
		'positions': [{'name': 'Data Architect',
      'field': 'Data Architecture',
      'time_experience': None},
    {'name': 'Data Mesh/Fabric Specialist',
      'field': 'Data Architecture',
      'time_experience': None}],
    'main_position': {'name': 'Data Architect',
      'field': 'Data Architecture',
      'time_experience': None},
    'main_position_name_variations': ['Data Architect',
    'Data Mesh Architect',
    'Data Fabric Architect'],
    'hard_skills': [{'description': 'Data Mesh concepts',
      'time_experience': None},
    {'description': 'Data Fabric concepts', 'time_experience': None},
    {'description': 'High-level architectural design', 'time_experience': None},
    {'description': 'Data as a Product standards', 'time_experience': None}],
    'soft_skills': ['Stakeholder management']},
  {'company_name': 'Starlight Gaming',
		'positions': [{'name': 'Software Engineer',
      'field': 'Data Engineering',
      'time_experience': None}],
    'main_position': {'name': 'Data Engineer',
      'field': 'Data Engineering',
      'time_experience': None},
    'main_position_name_variations': ['Data Engineer',
    'Pipeline Engineer',
    'Big Data Engineer'],
    'hard_skills': [{'description': 'Java/Kotlin or Scala',
      'time_experience': None},
    {'description': 'Google Cloud Dataflow / Apache Beam',
      'time_experience': None},
    {'description': 'BigQuery', 'time_experience': None},
    {'description': 'Looker', 'time_experience': None}],
    'soft_skills': ['Event Tracking',
    'Scalability',
    'Performance Optimization']}
]

STRUCTURED_CV = {
    'positions': [
         {'name': 'Data Engineer II', 'field': 'Data Engineering', 'time_experience': 24.0}, 
         {'name': 'Data Governance Analyst II', 'field': 'Data Governance', 'time_experience': 6.0}
         ], 
    'main_position': {'name': 'Data Engineer II', 'field': 'Data Engineering', 'time_experience': 30.0},
    'main_position_name_variations': ['Data Engineer II'], 
    'hard_skills': [
        {'description': 'GCP services (BigQuery, Composer, Cloud Storage, Cloud Run, Pub/Sub, Dataform, Dataflow, Dataplex, Datastream)', 'time_experience': 24.0}, 
        {'description': 'AWS services (S3, Glue, Athena, DynamoDB)', 'time_experience': 17.0}, {'description': 'Azure services', 'time_experience': 17.0}, 
        {'description': 'Python', 'time_experience': 30.0}, 
        {'description': 'SQL', 'time_experience': 30.0}, 
        {'description': 'Apache Beam', 'time_experience': 24.0}, 
        {'description': 'IaC tools (GitHub, Docker)', 'time_experience': 24.0}, 
        {'description': 'CI/CD automations (GitHub Actions)', 'time_experience': 24.0}, 
        {'description': 'ETL processes', 'time_experience': 30.0}, 
        {'description': 'ELT processes', 'time_experience': 17.0}, 
        {'description': 'Data Mesh architecture', 'time_experience': 24.0}, 
        {'description': 'Medallion Model layers', 'time_experience': 24.0}, 
        {'description': 'Data Lakehouse Architecture', 'time_experience': 17.0}, 
        {'description': 'Data Warehouse Management (GCP BigQuery)', 'time_experience': 12.0}, 
        {'description': 'Data Modeling (star/snowflake schemas, Data Entity Relationship models)', 'time_experience': 12.0}, 
        {'description': 'Observability Solutions (Data Lineage, Apache Airflow)', 'time_experience': 24.0}, 
        {'description': 'Shell scripting', 'time_experience': 24.0}, 
        {'description': 'Bash files', 'time_experience': 24.0}, 
        {'description': 'Data Governance policies', 'time_experience': 6.0}, 
        {'description': 'Data Quality Assurance', 'time_experience': 6.0}, 
        {'description': 'Data Profilling', 'time_experience': 6.0}, 
        {'description': 'Oracle', 'time_experience': None}, 
        {'description': 'PostgreSQL', 'time_experience': None}, 
        {'description': 'Firestore', 'time_experience': None}, 
        {'description': 'SFTP servers', 'time_experience': None}, 
        {'description': 'APIs', 'time_experience': None}, 
        {'description': 'Salesforce', 'time_experience': None}, 
        {'description': 'Uber', 'time_experience': None}, 
        {'description': 'Pandas', 'time_experience': None}, 
        {'description': 'Numpy', 'time_experience': None}, 
        {'description': 'Object Oriented Programming', 'time_experience': None}, 
        {'description': 'Infrastructure as Code', 'time_experience': 17.0}, 
        {'description': 'Codepipeline', 'time_experience': None}, 
        {'description': 'EFS', 'time_experience': None}, 
        {'description': 'Lambda function', 'time_experience': None}, 
        {'description': 'ECR', 'time_experience': None}, 
        {'description': 'ECS', 'time_experience': None}, 
        {'description': 'Docker', 'time_experience': None}, 
        {'description': 'Git', 'time_experience': None}, 
        {'description': 'Jira', 'time_experience': None}, 
        {'description': 'Confluence', 'time_experience': None}, 
        {'description': 'ServiceNow', 'time_experience': None}, 
        {'description': 'Power BI', 'time_experience': None}, 
        {'description': 'Looker Studio', 'time_experience': None}], 
    'soft_skills': ['Communication', 'Collaboration', 'Problem-solving', 'Agile methodology', 'Stakeholder management', 'Mentoring'], 
    'creation_timestamp': '2026-02-03 01:49:40'
}