services:

  api:
    build: ./api
    ports:
      - "8000:80"
    volumes:
      - ./api:/code
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redis-commander:
      image: rediscommander/redis-commander
      ports:
          - "8081:8081"
      environment:
          - REDIS_HOSTS=local:redis:6379

  celery-worker:
    build: ./api
    command: celery -A celery_app worker --loglevel=info --concurrency=2
    working_dir: /code/app
    volumes:
      - ./api:/code
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis